### ISSUE TITLE
Archive update: forbidden wildcards

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#50]
_g) No wildcard values shall be accepted, an INVALID error is returned in this case._

Could those forbidden wildcard values be listed?

**Comment by SamCooper** [comment]
Changed to:

"No wildcard values shall be accepted in the object type, the domain, and the object instance identifier, an INVALID error is returned in this case and no objects are updated.
"

Is this ok?

**Comment by DavidFeliot** [comment]
Does it mean that the ObjectDetails could contain wildcards in order to match several objects?

**Comment by SamCooper** [comment]
It can contain wildcards, but the object details fields are not used to match objects to update because the udpate operation now states:

"The object instance identifier contained in the ArchiveDetails, combined with the object type and domain from the request, shall be used to match objects."

So you could set the object details to contain wildcards if you wanted.

**Comment by DavidFeliot** [comment]
Does it make sense to update an object with an ObjectDetails containing wildcards?

**Comment by SamCooper** [comment]
Well the meaning of those fields is service specific so I guess it could be possible.

**Comment by DavidFeliot** [comment]
Is it a good idea to allow wildcards in the source ObjectId ('*' and '0') or in the 'related' field ('0')?

**Comment by SamCooper** [comment]
Like I said, they are service specific so it would depend. I don't think the Archive should put the restrictions on these fields as we don't know how we may want to use them in the future.

**Comment by DavidFeliot** [comment]
COM could put the restrictions on these fields.
Why would a service require to assign the value '0' to the 'related'? Could it be NULL instead? '0' could be forbidden as a related. It would be clearer.

**Comment by SamCooper** [comment]
I do not know why a service would want to assign '0' to the related field but it would mean 'all' rather than 'none'. This might make sense to a specific service. Putting the restriction in may make it clearer but I don't think it would be a good idea.

Would it affect the archive service it being '0'?

**Comment by DavidFeliot** [comment]
No, the issue is just that it was not clear.

My only concern is that in a query, '0' matches everything (as it is a wildcard), not only '0'. So if you are looking for the objects that have a '0' related (related to "all") then you will get not only those objects but also all the other ones that point to a single related (that are not related to "all"). Is that consistent?

**Comment by DavidFeliot** [comment]
And also if you are looking for the objects that are related to 'x' then you will miss the ones that have a '0' related, unless 'x' (in a query) matches '0' (from a stored object)?

**Comment by SamCooper** [comment]
So the issue would be that we couldn't search for one that uses the wildcard as a value because it would end up matching all.

That makes sense, I'll add in the restriction about these values in the generic COM section I'm going to add.

**Comment by SamCooper** [comment]
Done.
