### ISSUE TITLE
Object body type

### ISSUE THREAD

**Issue by DavidFeliot** [SamCooper/COM_SPEC_RIDS#9]
Is the term 'body' defined by the COM document?

The term 'payload' is also used by the Event service. Are 'body' and 'payload' synonymous?

What are the allowed types of an object body/payload? Any MAL data types? Abstract data types? Empty?

**Comment by SamCooper** [comment]
It should be the same as for the MAL, as in any type. 

What are your thoughts on a good term to use, I'm not happy with body (because its optional), and payload sounds a bit too spacecraft-y?

**Comment by DavidFeliot** [comment]
Should abstract types be allowed? If so, then the archive operation 'retrieve' cannot return a List<Element> through the Invoke pattern. Moreover there would be also a problem about the ordering of the query results for a given object type.

Could it simply be 'value', i.e. the object value?

**Comment by SamCooper** [comment]
Actually thinking about it, when we did the initial work on the new COM, Nicolas was quite specific that the 'type' of an object was static and never abstract so I think we should restrict this to concrete types only.

I don't think value would work because the event does not need to have this body part.

**Comment by SamCooper** [comment]
Ok, changed all references to use the term 'body' for both object and event.
